exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('Beautyspa').del(),

    knex('Beautyspa').insert({id: 1, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 2, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 3, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 4, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 5, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 6, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 7, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 8, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty2.jpg",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"}),
    knex('Beautyspa').insert({id: 9, Vendor: "Vendoe1", Title: "Just Rs. 599 for Hair Cut + Head Massage + Hair Spa + Organic Facial + Beard Trimming / Shaving from Estilo Unisex Salon, Pallimuku ", Deal_price: "$500",Old_price: "$1000", Category: "Beautyspa",Image1:"../images/beauty.png",Image2:"../images/hotel2.1.jpg",Image3:"../images/hotel1.jpg",Image4:"../images/hotel4.jpg",Rating:"3",people_bought:"230",People_Reviewed:"100",Valid:"28 Jan, 2017 - 28 Apr, 2017"})

);
};


    // Inserts seed entries
